services:
  # Nodo 1 - Puerto 5001
  nodo-uno:
    build: .
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - NODE_NAME=Nodo-1
    volumes:
      - ./data/node1:/app/data
    container_name: nodo-uno
    restart: unless-stopped

  # Nodo 2 - Puerto 5002
  nodo-dos:
    build: .
    ports:
      - "5002:5000"
    environment:
      - PORT=5000
      - NODE_NAME=Nodo-2
    volumes:
      - ./data/node2:/app/data
    container_name: nodo-dos
    restart: unless-stopped

  # Nodo 3 - Puerto 5003
  nodo-tres:
    build: .
    ports:
      - "5003:5000"
    environment:
      - PORT=5000
      - NODE_NAME=Nodo-3
    volumes:
      - ./data/node3:/app/data
    container_name: nodo-tres
    restart: unless-stopped

networks:
  default:
    name: nodos-productos
